### ISSUE TITLE
db:seed fails

### ISSUE THREAD

**Issue by idanci** [bbenezech/dummy_app#2]

**Comment by canopyone** [comment]
Rake DB:SEED   FAILS

 bundle exec rake db:seed --trace
*\* Invoke db:seed (first_time)
*\* Execute db:seed
*\* Invoke db:abort_if_pending_migrations (first_time)
*\* Invoke environment (first_time)
*\* Invoke rails_admin:disable_initializer (first_time)
*\* Execute rails_admin:disable_initializer
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
*\* Execute environment
*\* Invoke db:load_config (first_time)
*\* Execute db:load_config
*\* Execute db:abort_if_pending_migrations
rake aborted!
undefined method `[]' for nil:NilClass
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/mlb-0.6.1/lib/mlb/team.rb:62:in`results_to_team'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/mlb-0.6.1/lib/mlb/team.rb:29:in `all'
/home/uday/Desktop/dummy/db/seeds.rb:11:in`<top (required)>'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in`block in load'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in`load'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.9/lib/rails/engine.rb:520:in `load_seed'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/railties/databases.rake:333:in`block (2 levels) in <top (required)>'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:227:in `call'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:227:in`block in execute'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:222:in `each'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:222:in`execute'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/home/uday/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:159:in `invoke_with_call_chain'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/task.rb:152:in`invoke'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:141:in `invoke_task'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:99:in`block (2 levels) in top_level'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:99:in `each'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:99:in`block in top_level'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:108:in `run_with_threads'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:93:in`top_level'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:71:in `block in run'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:158:in`standard_exception_handling'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/lib/rake/application.rb:68:in `run'
/home/uday/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.0.2/bin/rake:37:in`<top (required)>'
/home/uday/.rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `load'
/home/uday/.rvm/gems/ruby-1.9.3-p448/bin/rake:19:in`<main>'
/home/uday/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
/home/uday/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`<main>'
Tasks: TOP => db:seed
